version: '3'
services:
  pythonserver:
    build:
      context: ./pythonserver
      dockerfile: Dockerfile
    ports:
      - 3002:3002

    environment:
      - PORT=3002
      - ENVIRONMENT=production
